---
title: "Fire"
format: html
editor: visual
---

## Fire Visualization

```{r}
#load packages
library(tidyverse)
library(readr)
library(ggplot2)
library(dplyr)
library(viridis)    

```

```{r}
#load files
ConfirmedSite <- read_csv("~/Desktop/GitHub/Focal_Project_STREAMS/ConfirmedSite.csv")
```

```{r}
##Boxplots of all cram scores
#plot all index to identify patterns
ConfirmedSite %>%
  ggplot(aes(x=`Pre/Post_Fire`, y=indexscore)) +
  geom_boxplot()+
  geom_point(aes(color=`Fire/Control`))

#plot all buffer to identify patterns
ConfirmedSite %>%
  ggplot(aes(x=`Pre/Post_Fire`, y=bufferlan)) +
  geom_boxplot()+
  geom_point(aes(color=`Fire/Control`))

#plot all hydrology to identify patterns
ConfirmedSite %>%
  ggplot(aes(x=`Pre/Post_Fire`, y=hydrology)) +
  geom_boxplot()+
  geom_point(aes(color=`Fire/Control`))

#plot all physical to identify patterns
ConfirmedSite %>%
  ggplot(aes(x=`Pre/Post_Fire`, y=physical)) +
  geom_boxplot()+
  geom_point(aes(color=`Fire/Control`))

#plot all biotic to identify patterns
ConfirmedSite %>%
  ggplot(aes(x=`Pre/Post_Fire`, y=biotic_str)) +
  geom_boxplot()+
  geom_point(aes(color=`Fire/Control`))


```

```{r}
#Index grid
ggplot(data = ConfirmedSite, aes(x=fct_rev(`Pre/Post_Fire`), y=indexscore, color=`Fire/Control`)) +
  geom_point() + 
  geom_line(aes(group=Pair_ID)) +
  facet_wrap(~ Group_ID) 

```

```{r}
#buffer grid
ggplot(data = ConfirmedSite, aes(x=fct_rev(`Pre/Post_Fire`), y=bufferlan, color=`Fire/Control`)) +
  geom_point() + 
  geom_line(aes(group=Pair_ID)) +
  facet_wrap(~ Group_ID) 

```

```{r}
#hydrology grid
ggplot(data = ConfirmedSite, aes(x=fct_rev(`Pre/Post_Fire`), y=hydrology, color=`Fire/Control`)) +
  geom_point() + 
  geom_line(aes(group=Pair_ID)) +
  facet_wrap(~ Group_ID) 

```

```{r}
#physical grid
ggplot(data = ConfirmedSite, aes(x=fct_rev(`Pre/Post_Fire`), y=physical, color=`Fire/Control`)) +
  geom_point() + 
  geom_line(aes(group=Pair_ID)) +
  facet_wrap(~ Group_ID) 

```

```{r}
#biotic grid
ggplot(data = ConfirmedSite, aes(x=fct_rev(`Pre/Post_Fire`), y=biotic_str, color=`Fire/Control`)) +
  geom_point() + 
  geom_line(aes(group=Pair_ID)) +
  facet_wrap(~ Group_ID) 

```
